name: 'Submodules Sync'

on:
  repository_dispatch:
    types: [trigger-common-update]
  #trigger by hand
  workflow_dispatch:

jobs:
  sync:
    name: 'Submodules Sync'
    env:
      GitBranch: automatic-update
      MainBranch: main
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      id: checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GHA_UPDATE }}
        submodules: true

    #Setup git
    - name : Set up git
      id: set_up_git
      if: steps.checkout.outcome == 'success'
      run: |
        git config --global user.name 'Git bot'
        git config --global user.email 'bot@noreply.github.com'
        git fetch

    #Reset branch to main
    - name : Reset branch
      id: reset_branch
      if: steps.checkout.set_up_git == 'success'
      run: |
        git switch $GitBranch
        git reset origin/$MainBranch --hard
        git switch $MainBranch
    
    # Update references
    - name: Update references 
      id: update_ref
      if: steps.checkout.reset_branch == 'success'
      run: |
        git pull --recurse-submodules
        git submodule update --remote --recursive

    - name: Commit update
      id: commit
      if: steps.update_ref.reset_branch == 'success'
      run: |
        git switch $GitBranch
        git commit -am "Auto updated submodule references" && git push || echo "No changes to commit"
        git push --set-upstream origin $GitBranch -f
        

    - name: create pull request
      id: pr
      if: steps.commit.reset_branch == 'success'
      run: gh pr create -B $GitBranch -H main --title 'Merge automatic-update into main' --body 'Created by Github action'
      env:
          GITHUB_TOKEN: ${{ secrets.GHA_UPDATE }}
